source ~/.vim/configuration.vim
source ~/.vim/coc-settings.vim
source ~/.vim/airline.vim
source ~/.vim/folding.vim
source ~/.vim/git.vim
source ~/.vim/nerdtree.vim
source ~/.vim/treesitter.lua
source ~/.vim/windows.vim
source ~/.vim/moves.vim
source ~/.fzf/plugin/fzf.vim
source ~/.vim/fzf.vim
source ~/.vim/custom-highlights.vim
source ~/.vim/custom-mappings.vim
source ~/.vim/blamer.vim
